EricKwong/chronos

router/index.js, router/routes/artists.js, server.js
=> search for artist routes.

public/js/app.js, public/js/views/main_artists.js, router/index.js, router/routes/album_tracks.js, router/routes/artist_albums.js, router/routes/artists.js
=> Search results

server.js
=> cleaned up server.js

public/js/app.js, public/js/views/main_artists.js, router/routes/album_tracks.js, router/routes/artist_albums.js
solved issue of linking tracks to collaborating artists WOOT WOOT WOOT
=> solved issue of linking tracks to collaborating artists WOOT WOOT WOOT

public/index.html
added elements to each template and made some small changes to John's skeleton
=> added templates and small changes

server.js
=> enabled frontend

public/index.html, public/js/views/main_artist_selection.js, public/js/views/main_artists.js
Editted/added main artist selection template. Made basic main artists collection view and artist search view.
=> Main artist view

router/routes/artist_albums.js
=> added artist image URLs to collabArtist objects

public/index.html, public/js/app.js, public/js/views/main_artist_selection.js, public/js/views/main_artists.js, router/routes/artists.js
linked artists search button to fetch data from api route
=> linked artist search with fetching data from api

public/js/views/main_artists.js
fixed search results emptying issue
=> fixed search results emptying issue

public/index.html, public/js/views/main_artist.js, public/js/views/main_artist_selection.js, public/js/views/main_artists.js
show main artist view working.
=> show main artist working

public/js/views/collab_artist.js
starter code for single collab artist
=> added starter code to single collab artist view

public/js/app.js, public/js/views/collab_artists.js, public/js/views/main_artist_selection.js, public/js/views/main_artists.js
=> Collab artists collection view

migrations/20150403105728-create-playlists.js, migrations/20150403105935-create-songs.js, models/playlists.js, models/songs.js
created migration and models for playlists and songs
=> created migration and models for playlists and songs

migrations/20150403110657-playlists_songs.js
created playlists and songs relation table migration
=> created playlists and songs relation table migration

models/playlists.js, models/songs.js
created playlists and songs associations in models
=> model associations

router/index.js, router/routes/songs.js
=> added songs route

router/index.js, router/routes/playlists.js
resolved merge conflict and added relationship routes.
=> Playlist routes

public/index.html, public/js/app.js, public/js/collections/playlist.js, public/js/models/playlist.js, public/js/views/playlist.js
=> Playlist view

router/routes/get_collabs.js
able to grab up to 40 albums; still need to fix several issues
=> get_collabs.js -- router update

router/routes/get_collabs.js
=> router works with no known errors

public/css/style.css, public/index.html, public/js/views/playlist.js, public/js/views/playlist_songs.js
added expandable click event to playlist and css fixes
=> expandable playlist

public/index.html, public/js/views/collab_artist.js, public/js/views/collab_artists.js, router/routes/get_collabs.js
=> John backbone

public/css/style.css, public/index.html
Got the add track button lining up with track name for the most part. Also did some refactoring and clean up in style.css and index.html.
=> track lists and buttons looking semi-good

public/css/style.css, public/index.html, public/js/app.js, public/js/views/collab_artist.js, public/js/views/playlist.js, public/js/views/playlist_song.js
added delete button for tracks
=> added delete button

router/routes/get_collabs.js, router/routes/search_artists.js
solved several errors. sorted collabs based on # of tracks
=> No known router errors
